### ISSUE TITLE
showing lock ui stays active after reload in simulator

### ISSUE THREAD

**Issue by noahdesu** [auth0/react-native-lock#100]
First off, thank you for providing this package it has been very helpful. I'm having an issue that isn't a blocker, but has proven to be a bit of an annoyance when developing in the simulator.

When I show the Lock UI and then reload the simulator the Lock UI screen is still active. I would have expected it to be closed after reloading the application. For instance normally when I reload the UI navigates back to the initiate route/nav state, but reloading after showing Lock UI doesn't result in this behavior.

 Is there an option I can set to do this, or a close method I could use to reset the UI state?

**Comment by hzalaz** [comment]
@noahdesu I am afraid this is not possible since this library wraps the native versions of Lock (written in ObjC & Java) so the views are not part of RN lifecycle. We haven't found a way to listen to this event to hide it automatically but maybe in your component you can hide lock if the `component{Wil,Did}lUnmount` is triggered on refresh

**Comment by hzalaz** [comment]
Closing this one please reopen if needed
