### ISSUE TITLE
Ios callback URL mismatch

### ISSUE THREAD

**Issue by Eugenelee** [auth0/react-native-lock#153]
Hi all. 
I am having issues with IOS.  i followed the documentation to setup my project.  android works perfectly but not IOS.  i a got a browser screen that said callback URL mismatch the url '**org.reactjs.native.my-project'** is not in the list of allowed callbackURLs. 
I don't have any experience with Objective-C. Can anyone guide me to solve this ?

**Comment by lukecwilliams** [comment]
Try adding it to your callback URLs on the Auth0 website.

**Comment by lukecwilliams** [comment]
@hzalaz Hernan - I can't find what URL to use either.  I see "org.reactjs.native.example.MyApp://myDomain.auth0.com/ios/org" and then the page is cut off.  

What callback URL should we use with useBrowser setting?

**Comment by lukecwilliams** [comment]
Ok, I found the domain by clicking "Technical Details" at the bottom of the Auth0 invalid callback URL error page.  Now I'm getting "Safari cannot open the page because the address is invalid."

Any help making sure the address is valid?  We don't have control over it besides the base domain, unless I can change some kind of config.

**Comment by hzalaz** [comment]
The format is `{bundle identifier}://{auth0 domain}/ios/{bundle identifier}/callback`

so you need to replace it with your app values:

- bundle identifier: its the id of the app and can be found in the Info.plist file and its the one used by iOS to identify your app, in your case is the default RN sets (I'd probably change it but I am talking as an iOS dev)
- auth0 domain: your account domain found in the dashboard

Your error seems to be that you didn't fully follow the instructions in the readme https://github.com/auth0/react-native-lock#ios-2

**Comment by lukecwilliams** [comment]
Thank you @hzalaz - I had inserted {bundle identifier} verbatim instead of filling it in.

Currently the readme.md doesn't contain your instruction about the callback.  I submitted a pull request with suggested change for the two issues I had (and the other member of this thread).

https://github.com/auth0/react-native-lock/pull/155

**Comment by lukecwilliams** [comment]
@Eugenelee Did you solve your problem?

I suggest closing this thread as a workable solution has been posted.

**Comment by Eugenelee** [comment]
@lukecwilliams  Yes , i did!  @hzalaz  thanks for the info.
