### ISSUE TITLE
Error evaluating 'LockModule.init'

### ISSUE THREAD

**Issue by aviadhahami** [auth0/react-native-lock#65]
Hi, 
I'm trying to use your module yet I hit this error (followed your instructions 100%)

![image](https://cloud.githubusercontent.com/assets/7353632/16136081/666ed7d4-3430-11e6-9504-5042ae79bdb4.png)

Any resolutions to this?

Thanks

**Comment by hzalaz** [comment]
@aviadhahami can you provide a little more context information like how you are instantiating Lock in your code?

**Comment by aviadhahami** [comment]
@hzalaz yes, sure (sorry for not doing this initially).

I have a component called App which instantiates the `Auth0` module like this (nothing fancy):

```javascript
import React, { Component } from 'react'
import {View, Text} from 'react-native'
import Auth0Lock from 'react-native-lock'


class App extends Component{
	constructor(props){
		super(props)
		this.state = {
			profile:'',
			token:'',
		}
	}

	componentWillMount(){
	}
	componentDidMount(){
		let lock = new Auth0Lock({clientId: 'xxxxxx', domain: 'aviadhahami.eu.auth0.com'});
		lock.show({}, (err, profile, token) => {
			if (err) {
				console.log(err);
				return;
			}
			// Authentication worked!
			console.log('Logged in with Auth0!');
			this.setState({
				profile: profile,
				token: token,
			})
		});
	}

	render(){
		console.log(this.state.profile)
		console.log(this.state.token)
		return (
			<View>
				<Text>
					UN: {this.state.profile.name}
				</Text>
				<Text>
					Tkn: {this.state.token}
				</Text>
			</View>
		)
	}
}

export default App
```

My `package.json` has this:
```javascript
"dependencies": {
    "react": "^15.1.0",
    "react-native": "0.27.2",
    "react-native-lock": "^0.3.0"
  }
```
Rather than this, I've followed what you guys stated on your [Readme](https://github.com/auth0/react-native-lock/blob/master/README.md) (regarding the gradle and the manifest)

**Comment by jniemin** [comment]
I ran in to same issue. I did installation using rnpm  `rnpm link react-native-lock`. After opening the new  workspace created by cocoapods I got this same error. I got it working when I manually added A0RNLock.xcodeproj from under node_modules/react-native-lock/ios/ to my libraries and also added libA0RNLock.a to "link binary with libraries". 

I wonder if this step is missing from the instructions or should this be happening automatically?

**Comment by aviadhahami** [comment]
@jniemin imo it should happen during the `rnpm link` process..
@hzalaz - Any updates?

**Comment by sagic** [comment]
+1

**Comment by sagic** [comment]
found the problem. when running the rnpm link automation it's skipping a stage.
i followed the manual instructions in the readme.md file to see what is wrong.
apparently, the LockReactPackage is missing from the 'getPackages' method.
it should be in MainApplication.java instead of MainActivity.java as instructed (and probably as the linker is trying to init).

MainApplication.java:
`
...
import com.auth0.lock.react.LockReactPackage;
...
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new LockReactPackage()
      );
    }
...
`

**Comment by lanceblais** [comment]
The first time I read this, I updated MainActivity.java because I didn't read it the whole way. 

Don't make that mistake. It goes in MainApplication.java. 

@sagic This worked for me as well once I got the file right! 

Thanks

**Comment by hzalaz** [comment]
This is because RN introduced yet another breaking change in [v0.29](https://github.com/facebook/react-native/releases/tag/v0.29.0) by moving the place where native modules are registered to a custom Android Application object. As @lanceblais said, this should be done in `MainApplication.java` (We'll update the manual installation steps).

If you are using rnpm, seems it's bundled in `react-native-cli`, so calling `react-native link` is the recommended step now (until it changes again). Just make sure you are using version [0.29.2](https://github.com/facebook/react-native/releases/tag/v0.29.2) of react-native since they fixed rnpm to work with `MainApplication.java`.

In iOS rnpm (or `react-native link` now) should handle adding the xcodeproj itself and I see no breaking changes in iOS so far.

Closing this now, feel free to open new issues for iOS if it's not working with some details

**Comment by MaxwellGover** [comment]
@sagic I tried what you suggested and am still getting the error :( I'm on Android as well. MainApplication.java looks like this. 

`
import com.auth0.lock.react.LockReactPackage;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new LockReactPackage()
          new OAuthManagerPackage(),
          new FirestackPackage(),
          new RCTCameraPackage()
      );
    }
  };`

**Comment by lukecwilliams** [comment]
If you see this error on iOS, I posted the fix that worked for us at:

https://github.com/auth0/react-native-lock/issues/133

**Comment by iboxgithub** [comment]
Thanks a lot: I had this issue on Ubuntu because while trying to link I always had an issue because of CocoaPods (impossible to install)
So actually the mannual installation steps fixed the issue for me!

**Comment by adam8810** [comment]
For those who are going down the same path as I did and found this issue. Please note that the `create-react-native-app` project is not intended for projects that need to link to native code such as this one.
