### ISSUE TITLE
How to add Lock.framework?

### ISSUE THREAD

**Issue by conan52** [auth0/react-native-lock#72]
Hi all,
I tried install react-native-lock for my project. To step 2. Change to the A0RNLock.xcodeproj target tab Build Phases, and in the section Link Binary with Libraries click the + and add Lock.framework and make sure it's Status is set to optional. 
I use ios 9.3 when I click to + but not exist Lock.framework. How to add Lock.framework?
Thanks.

**Comment by conan52** [comment]
pls help me. I need it. Thanks

**Comment by jhabdas** [comment]
@conan52 Please check out other RN native modules and their manuals to understand how to set things up manually. You can also look at the [Pepperoni boilerplate](https://github.com/futurice/pepperoni-app-kit) for a working example of Auth0 integration in an RN app. And if you're using `react-native-cli@1.0.0` you can install Lock automagically for both iOS and Android by running `react-native link react-native-lock`. It'll take care of the Xcode stuff (most of it, anyway) automatically.

**Comment by grifotv** [comment]
I'm having the same issue as @conan52 - no `Lock.framework` available

<img width="402" alt="screen shot 2016-11-14 at 14 13 07" src="https://cloud.githubusercontent.com/assets/435351/20267869/8c5e99d8-aa74-11e6-9b54-8428b49421a4.png">

**Comment by jhabdas** [comment]
@grifotv what happens when you run the link command as noted in the documentation?

**Comment by grifotv** [comment]
@jhabdas it links fine, adding Podfile to iOS project and I get this final message `Pod installation complete! There are 4 dependencies from the Podfile and 5 total pods installed.`

**Comment by jhabdas** [comment]
@grifotv then you're all done :)

**Comment by jhabdas** [comment]
@hzalaz this feels like a non-issue. Care to close?

**Comment by hzalaz** [comment]
@grifotv why you want to link Lock.framework?

**Comment by grifotv** [comment]
@jhabdas @hzalaz thanks for the reply. I just tried to follow [these instructions](https://github.com/auth0/react-native-lock/#cocoapods-with-uses_framework-flag) where it says _"After setting up react-native-lock either Manually or using react-native cli you need.."_

I was under the impression it's a requirement - I did check the [Pepperoni boilerplate](https://github.com/futurice/pepperoni-app-kit) and their Xcode project doesn't really follow these steps, so I guess it's fine to just ignore this bit of instruction?

The reason why I tried to follow every single bit of instruction is due to a `** BUILD FAILED **` I get when running `react-native run-ios`. Essentially this same issue https://github.com/auth0/react-native-lock/issues/87#issuecomment-242914817, the app opens but with a build failed message.

<img width="952" alt="ios" src="https://cloud.githubusercontent.com/assets/435351/20269105/c2e39404-aa79-11e6-8eb8-e47ffcfa9ae1.png">

Should I just carry on and ignore this build failed message once it's not a blocker?

**Comment by hzalaz** [comment]
@grifotv that is only if you need to use frameworks for your iOS dependencies (by adding the `uses_framework!` flag in your Podfile). If you don't need it just remove it and run `pod update` and `react-native link` again just in case since it should work out of the box.

**Comment by grifotv** [comment]
@hzalaz even after running `pod update` and `react-native link` I still get the build failed message I'm afraid.

I removed `Podfile.lock` before running the commands.

**Comment by hzalaz** [comment]
@grifotv can't help you without knowing the details of your setup. Try starting from scratch and see what's different since by default you only need to run react-native link and everything should work.

If it's still an issue please open a new one with a sample I can debug
